# Generated by Django 5.0 on 2024-12-15 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be greater than 0.')]),
        ),
        migrations.AlterField(
            model_name='antique',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug can only contain lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='antique',
            name='stocks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Stocks cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='antique',
            name='title',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title can only contain letters, numbers, and spaces.', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='antique',
            name='year_made',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000, message='Year must be at least 1000.'), django.core.validators.MaxValueValidator(9999, message='Year must be a valid 4-digit number.')]),
        ),
    ]
