# Generated by Django 5.0 on 2024-12-15 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(help_text='First name must contain at least 2 characters.', max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name must contain at least 2 characters.', max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(help_text='Enter a valid phone number.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(help_text='Username must be at least 3 characters long.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, numbers, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$'), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
