# Generated by Django 5.0 on 2024-12-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('antiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PROCESSING', 'processing'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_status', models.CharField(choices=[('NOT_PAID', 'Not Paid'), ('PAID', 'Paid'), ('PENDING_PAY', 'Pending Payment'), ('REJECTED', 'Rejected'), ('FRAUD', 'Fraud'), ('TIMEOUT', 'Timeout'), ('PENDING_CHECK', 'Pending Check')], default='Pending Payment', max_length=300)),
                ('total_price', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=60)),
                ('zip', models.CharField(max_length=60)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('transaction_method', models.CharField(choices=[('BCA', 'BCA'), ('Mastercard', 'Mastercard'), ('BRI', 'BRI')], max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('order_note', models.CharField(blank=True, max_length=500)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.order')),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='antiques.antique')),
            ],
        ),
        migrations.CreateModel(
            name='order_note_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=3000)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.order')),
            ],
        ),
    ]
